nelmio_api_doc:
    documentation:
        info:
            title: calc.sio.localhost
            version: 0.0.1
        components:
        security:
            - Bearer: []
    areas:
        disable_default_routes: true
        path_patterns:
            - ^/(?!/api/doc$|$)
